### ISSUE TITLE
About implementation

### ISSUE THREAD

**Issue by dongqian0206** [haofuml/cyclical_annealing#2]
Hi. I am trying to run the source code based on Pytorch 0.4.1. 

I encountered a problem when the used model is the sa-vae:

> cudnn RNN backward can only be called in training mode

I noticed that you used Pytorch 0.2. Did you try the latest version of Pytorch?

**Comment by haofuml** [comment]
This part of implementation was based on Pytorch 0.2. There might be some issue if you run it on the latest version. Sorry about that inconvenience.
